// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuEr-7PWhyGDBaYwu0DbQFg7A3pgZdO-4',
    appId: '1:635833917757:web:99733533902da616ec2554',
    messagingSenderId: '635833917757',
    projectId: 'flutter-linknews',
    authDomain: 'flutter-linknews.firebaseapp.com',
    storageBucket: 'flutter-linknews.appspot.com',
    measurementId: 'G-YJVVXSCJMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq-B75jrYehB8lEWxKtW3wA6lOJP9R8Yw',
    appId: '1:635833917757:android:7377c96ee7d45ff1ec2554',
    messagingSenderId: '635833917757',
    projectId: 'flutter-linknews',
    storageBucket: 'flutter-linknews.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvdiYLLBUc78MThCKKQWzBObuNmR3AiqA',
    appId: '1:635833917757:ios:140383395a12a9c5ec2554',
    messagingSenderId: '635833917757',
    projectId: 'flutter-linknews',
    storageBucket: 'flutter-linknews.appspot.com',
    iosBundleId: 'com.example.linknews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvdiYLLBUc78MThCKKQWzBObuNmR3AiqA',
    appId: '1:635833917757:ios:5a1c4853e99b9e31ec2554',
    messagingSenderId: '635833917757',
    projectId: 'flutter-linknews',
    storageBucket: 'flutter-linknews.appspot.com',
    iosBundleId: 'com.example.linknews.RunnerTests',
  );
}
